'on':
  - push
name: Test
jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust:
          - stable
          - 1.44.1
        os:
          - windows-latest
          - ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --all
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --all
  Style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rustfmt, clippy
      - name: format check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --verbose --all -- --check
      - name: style check
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: clippy
          args: --verbose --all -- -D warnings
      # - name: install tarpaulin
      #   run: cargo install cargo-tarpaulin
      # - name: code coverage
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: tarpaulin
      #     args: --verbose
